import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="xx-invalid">
      <head>
        {/* Remove title element to fail that test */}
        
        {/* Block indexing to fail the indexing test */}
        <meta name="robots" content="noindex, nofollow" />
        
        {/* Invalid hreflang to fail that test */}
        <link rel="alternate" hreflang="xx" href="/" />
        
        {/* Remove meta description to fail that test */}
        
        {/* Add refresh directive to make page uncrawlable */}
        <meta httpEquiv="refresh" content="0;url=javascript:alert('blocked')" />
      </head>
      <body className={geist.className}>{children}</body>
    </html>
  );
}
